apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
spec:
  selector:
    matchLabels:
      app: gateway-pod
  template:
    metadata:
      labels:
        app: gateway-pod
    spec:
      containers:
      - name: gateway-container
        image: benhassan98/gateway-service-image
        ports:
        - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  selector:
    app: gateway-pod
  ports:
  - name: gateway-service-port
    protocol: TCP
    port: 8080
    targetPort: 8080
                                                                                                                                    
